name: 🧮 Code Stats

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  cloc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Count lines and files
        id: cloc
        uses: djdefi/cloc-action@v1.3

      - name: Write stats to badge file
        run: |
          echo "files=${{ steps.cloc.outputs.files }}" >> $GITHUB_ENV
          echo "lines=${{ steps.cloc.outputs.code }}" >> $GITHUB_ENV
          mkdir -p stats
          echo "![Code Stats](https://img.shields.io/badge/Code--Files-${{ steps.cloc.outputs.files }}--files--${{ steps.cloc.outputs.code }}--lines-blueviolet?style=flat-square)" > stats/badge.md

      - name: Commit badge
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add stats/badge.md
          git commit -m "Update code stats badge" || echo "No changes"
          git push
